spring:
  profiles:
    active: local
---
server:
  port: 8081

logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  config:
    activate:
      on-profile: local
  application:
    name: ing-user
  datasource:
    url: jdbc:mariadb://localhost:3306/example
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true    
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
      
minio: 
  host: minio
  port: 9000

pagehelper: # https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/en/HowToUse.md
  helper-dialect: mariadb   
  page-size-zero: false  
  offset-as-page-num: false  
  row-bounds-with-count: false  
  auto-runtime-dialect: false  
  close-conn: true  
  default-count: true
  reasonable: true # 범위가 넘어가는 pageNum이 들어올때 가능한 값으로 변경
    
---
server:
  port: 8080
        
logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  config:
    activate:
      on-profile: container
  application:
    name: ing-user
  datasource:
    url: ${MARIADB_URL}
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true    
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
    
minio: 
  host: minio
  port: 9000
  
pagehelper: # https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/en/HowToUse.md
  helper-dialect: mariadb   
  page-size-zero: false  
  offset-as-page-num: false  
  row-bounds-with-count: false  
  auto-runtime-dialect: false  
  close-conn: true  
  default-count: true
  reasonable: true # 범위가 넘어가는 pageNum이 들어올때 가능한 값으로 변경
 